### ISSUE TITLE
Kneel to count cells of a particular color

### ISSUE THREAD

**Issue by Bobolovewill** [ONLYOFFICE/plugin-macros#14]
There are many ways to use Excel, such as VBA
https://docs.microsoft.com/zh-cn/previous-versions/office/troubleshoot/office-developer/count-cells-number-with-color-using-vba
google sheets
function countColoredCells(countRange,colorRef) {
  var activeRange = SpreadsheetApp.getActiveRange();
  var activeSheet = activeRange.getSheet();
  var formula = activeRange.getFormula();
  
  var rangeA1Notation = formula.match(/\((.*)\,/).pop();
  var range = activeSheet.getRange(rangeA1Notation);
  var bg = range.getBackgrounds();
  var values = range.getValues();
  
  var colorCellA1Notation = formula.match(/\,(.*)\)/).pop();
  var colorCell = activeSheet.getRange(colorCellA1Notation);
  var color = colorCell.getBackground();
  
  var count = 0;
  
  for(var i=0;i<bg.length;i++)
    for(var j=0;j<bg[0].length;j++)
      if( bg[i][j] == color )
        count=count+1;
  return count;
};
onlyoffice?please

**Comment by ShockwaveNN** [comment]
@askonev Please take a look

**Comment by AlexeyMatveev686** [comment]
> et.getRange(color

Hello, let me help you.

You can use this macros for your task:

`
 function CountColoredCells (Range1, Range2)
    {
        // Range1 is the range where the search will be performed
        // Range2 is the range to be compared with when searching
        // (if there is more than one cell, it will only be compared with the first one)
        var count = 0;
        var color = Range2.GetFillColor();
        if (color !== "No Fill") {
            Range1.ForEach(function(cell) {
                var curColor = cell.GetFillColor();
                if (curColor !== "No Fill" && curColor.color === color.color)
                    count++;
            });
        }
        return count;
    }
`

Also you can can check how it works in my example file.
Good luck!
[new (1).xlsx](https://github.com/ONLYOFFICE/plugin-macros/files/6669886/new.1.xlsx)

**Comment by Bobolovewill** [comment]
Sorry, just replied. I still get an error after following your method of testing
![8P8H_YY98VNFDWS~T~E1TV4](https://user-images.githubusercontent.com/53516497/144770847-6993f074-2a89-42db-af51-310b09045e10.png)
.
![(70P85ELR7S4 Q72ZHV_CKS](https://user-images.githubusercontent.com/53516497/144770860-a0152f16-3dc4-44ad-b2b8-2a865beaafa5.png)

**Comment by askonev** [comment]
@Bobolovewill Hi! 

Please specify the version of the product on which you run the script.

**Comment by Bobolovewill** [comment]
Version: 5.6.5 (build:3)

**Comment by Bobolovewill** [comment]
> @Bobolovewill嗨！
> 
> 请指定运行脚本的产品版本。

Version: 5.6.5 (build:3)

**Comment by ShockwaveNN** [comment]
@Bobolovewill This is very very old version. Please update to current v6.4.2 and see if problems persists

**Comment by Bobolovewill** [comment]
> @Bobolovewill This is very very old version. Please update to current v6.4.2 and see if problems persists

Sorry for just replying, thanks everyone. The function worked after the upgrade, but I can't call it anywhere, I have to write it in advance. Last question, how to run macros automatically, or is there a shortcut?

**Comment by ShockwaveNN** [comment]
> run macros automatically, or is there a shortcut

We got autorun button:
![image](https://user-images.githubusercontent.com/668524/145786696-cbc0e9c8-460f-4825-8921-5710e7ebc214.png)
And marcos settings:
![image](https://user-images.githubusercontent.com/668524/145786769-75e8ecef-6d02-4bb6-a7e6-d43b361639f2.png)

Not sure how it works, not my area

Also, you can convert your macros to plugin (it use same code, but require some additional metadata) - you can run plugin with [autostart](https://api.onlyoffice.com/editors/config/editor/plugins#autostart)
