### ISSUE TITLE
vim like features.

### ISSUE THREAD

**Issue by logicalbhanu** [ONLYOFFICE/plugin-macros#53]
if it is possible to add vim like navigation and some basic functions of vim such as delete and block mode, then it would be very great for users who are used to of vim.
Thanks for your product, it is really nice, i am enjoying it.

**Comment by ShockwaveNN** [comment]
Hi, are you want vim enabled features in macros plugin only (since you created issue in macros repo)?

**Comment by logicalbhanu** [comment]
Sorry for the confusion, what i want is to have a plugin that can enable vim like features over the whole editor(when that plugin is enable).

**Comment by ShockwaveNN** [comment]
Do you aware of existing such pluing for MS office or other office suites? I know such plugins for IDE like VS Code or ItellejIdea, but our product is not IDE, so I'm not sure that it's feasible for office suite to do this rather complicated plugin

**Comment by logicalbhanu** [comment]
i heard something like viEmu exist for MS office, is there a way to use the same with only office?

**Comment by ShockwaveNN** [comment]
> viEmu exist for MS office

As far as I googled it - http://www.viemu.com/

> Compatible with Word & Outlook 2002 (XP) up to 2016 (32-bit)

So it ended support several years ago and seems that it's closed source solution, so we cannot use it's code

So I really don't think it's a thing we need to do, you can try to implement plugin like this yourself, but I'm almost sure it will not an easy task

**Comment by logicalbhanu** [comment]
> > you can try to implement plugin like this yourself, but I'm almost sure it will not an easy task
i would try it in my free time, btw thanks for your fast replies, i am closing this issue now.
